version: '3'



services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
# =================================================
# Client Gateway
# =================================================

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
# =================================================
# Products Microservice
# =================================================

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    
<<<<<<< HEAD
      
=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
# =================================================
# Orders Microservice
# =================================================

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
# =================================================
# Orders Database
# =================================================

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:

      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

<<<<<<< HEAD

=======
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
# =================================================
# Payments Microservice
# =================================================

  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
<<<<<<< HEAD
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
=======
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
>>>>>>> e307ed7 (update environment configuration and add payments microservice to docker-compose)
